import os
import subprocess
from datetime import datetime
from pathlib import Path

from setuptools import setup, find_packages

exec(open("deep_select/__version__.py").read())

# MACA port: `csrc/maca_topk.cu` is the shipping backend and the only
# translation unit in the default extension.
#
# The upstream `csrc/cuda_kernels/v3` (bf16) and `v3_fp32` trees have been
# ported to MACA (TMA -> cooperative `ldg`, mbarrier -> single buffer +
# `__syncthreads`, inline PTX -> MACA builtins).  They are built as one
# extension *per architecture* -- see `build_for_maca` -- because a config's
# shared memory footprint is only valid for the architecture it was sized for,
# and that is checked at compile time.
# `csrc/cuda_kernels/v3_cluster` is deleted: MACA has no cluster launch.
CUDA_SOURCES = [
    "csrc/maca_topk.cu",
]


def _upstream_sources():
    """The ported upstream topk kernel: host dispatch plus every instantiation.

    The instantiation files are generated by
    `scripts/generate_instantiations.py` and listed explicitly, as upstream
    lists them in its own `setup.py`: the set is what gets compiled, so it
    should be visible, not globbed.
    """
    sources = ["csrc/api.cpp"]
    for variant in ("v3", "v3_fp32"):
        directory = os.path.join("csrc", "cuda_kernels", variant, "instantiations")
        sources += sorted(
            os.path.join(directory, name)
            for name in os.listdir(directory)
            if name.endswith(".cu")
        )
    return sources


def _maca_root() -> str:
    return os.environ.get("MACA_HOME") or os.environ.get("MACA_PATH") or "/opt/maca"


def build_for_maca():
    """Build the extensions with the MACA toolchain.

    Device code is compiled by `mxcc` (MACA's nvcc equivalent), which torch's
    CUDAExtension already selects because `CUDA_HOME` resolves to
    `$MACA_PATH/tools/cu-bridge` in this environment.  The CUDA-specific
    `-gencode arch=compute_100a,code=sm_100a` flags have no meaning on MACA
    and are replaced by `--offload-arch=xcore<N>`.

    Which architectures get built comes from `CUCC_TARGETS` (default
    `native`), the same variable and meaning as the host repository's
    `build.sh`.

    The ported upstream kernels are opt-in via `DEEP_SELECT_BUILD_UPSTREAM`,
    and are then built as **one extension per architecture**, because each is
    gated on the shared memory capacity of the architecture it targets: a
    config that cannot fit is meant to be a compile error, and that only works
    if a compilation targets exactly one architecture.  (`--offload-arch`
    overrides `CUCC_TARGETS` in the environment, so passing it explicitly per
    module keeps the modules independent of each other's builds.)

    Opt-in because that gate is currently red almost everywhere: of upstream's
    five config tuples only one fits 128 KiB and none fits 64 KiB, so a default
    build would fail on every architecture this project ships for -- taking the
    working `maca_c` extension down with it.  The gate's job is to reject an
    upstream build that cannot launch, not to block the shipping backend; turn
    it on once per-architecture tuples exist.
    """
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CUDA_HOME

    from deep_select._arch import CAPACITY_BYTES, family_of_target, resolve_targets

    assert CUDA_HOME is not None, "PyTorch must provide a CUDA/MACA toolchain"

    maca_root = _maca_root()
    this_dir = os.path.dirname(os.path.abspath(__file__))
    targets = resolve_targets(os.environ.get("CUCC_TARGETS"))

    include_dirs = [
        os.path.join(this_dir, "csrc"),
        os.path.join(maca_root, "include"),
        os.path.join(maca_root, "tools", "cu-bridge", "include"),
    ]

    def compile_args(target):
        args = [
            "-O3",
            "-std=c++20",
            "-DNDEBUG",
            "-Wno-deprecated-declarations",
            "--use_fast_math",
            # `--use_fast_math` implies FTZ, so it is turned back off here.
            # The ranking path cannot care either way: it is pure integer
            # manipulation of the key (`__float_as_uint` plus integer ops),
            # and FTZ only governs floating-point arithmetic and conversion
            # results.  Keeping it off keeps the one float conversion in the
            # kernel -- `__float2bfloat16` of `value_oob_fill_value` -- exact
            # for a denormal fill instead of flushing it to zero.
            "--ftz=false",
            f"--offload-arch={target}",
            # `__MACA_ARCH__` is only defined in the device pass, but the
            # capacity constant lives in `structs.h`, which every translation
            # unit here includes -- so the value has to be spelled out on the
            # command line.  It carries the same number the toolchain derives,
            # and setup.py sets both from the same loop iteration.
            f"-DDEEP_SELECT_NATIVE_ARCH={family_of_target(target)}",
        ]
        return args + [f"-I{d}" for d in include_dirs]

    build_upstream = bool(os.environ.get("DEEP_SELECT_BUILD_UPSTREAM"))

    ext_modules = []
    for target in targets:
        family = family_of_target(target)
        capacity_kib = CAPACITY_BYTES[family] // 1024
        # The shipping hand-written kernel has no capacity gate; it is built
        # for the first target only, which is what "the build machine's
        # architecture" means today.
        if target == targets[0]:
            ext_modules.append(
                CUDAExtension(
                    name="deep_select.deep_select_cuda",
                    sources=CUDA_SOURCES,
                    include_dirs=include_dirs,
                    extra_compile_args={
                        "cxx": [
                            "-O3",
                            "-std=c++17",
                            "-DNDEBUG",
                            "-Wno-deprecated-declarations",
                        ],
                        "nvcc": compile_args(target),
                    },
                    extra_link_args=[
                        f"-L{maca_root}/lib",
                        f"-Wl,-rpath,{maca_root}/lib",
                    ],
                )
            )
        if not build_upstream:
            continue
        # The ported upstream kernel, per architecture: its config table is
        # only valid for a given capacity, and `run_topk_select_kernel` checks
        # that at compile time.
        ext_modules.append(
            CUDAExtension(
                name=f"deep_select.deep_select_upstream_{target}",
                sources=_upstream_sources(),
                include_dirs=include_dirs,
                extra_compile_args={
                    "cxx": [
                        "-O3",
                        "-std=c++17",
                        "-DNDEBUG",
                        "-Wno-deprecated-declarations",
                        f"-DDEEP_SELECT_NATIVE_ARCH={family}",
                    ],
                    "nvcc": compile_args(target),
                },
                extra_link_args=[
                    f"-L{maca_root}/lib",
                    f"-Wl,-rpath,{maca_root}/lib",
                ],
                define_macros=[("DEEP_SELECT_TARGET", f'"{target}"')],
            )
        )
        print(f"deep_select: building upstream xcore{family} "
              f"({capacity_kib} KiB shared memory) for {target}")

    if not build_upstream:
        print("deep_select: building the maca_c backend only; "
              "set DEEP_SELECT_BUILD_UPSTREAM=1 to also build the ported upstream "
              "kernel (see build_for_maca for why that gate is off by default)")

    return (ext_modules, BuildExtension.with_options(use_ninja=True))


try:
    cmd = ["git", "rev-parse", "--short", "HEAD"]
    git_rev = subprocess.check_output(cmd, stderr=subprocess.DEVNULL).decode("ascii").rstrip()
except Exception:
    # e.g. building from a source tarball that has no `.git`. Keep the version
    # a valid PEP 440 local version in that case.
    git_rev = "unknown"

datetime_rev = datetime.now().strftime("%Y%m%d.%H%M%S")

ext_modules, build_ext = build_for_maca()

setup(
    name="deep_select",
    version=f"{__version__}+{git_rev}.{datetime_rev}",
    packages=find_packages(include=["deep_select"]),
    ext_modules=ext_modules,
    cmdclass={"build_ext": build_ext},
    zip_safe=False,
)
