import os
import subprocess
from datetime import datetime
from pathlib import Path

from setuptools import setup, find_packages

exec(open("deep_select/__version__.py").read())

# The kernel tree is split by architecture, and each half is a kernel rather
# than a variant of one:
#
#   csrc/xcore1000/   the hand-written MACA kernel (`maca_topk.cu`).  No
#                     capacity gate and no architecture-specific code; this is
#                     what a 64 KiB part runs.
#   csrc/xcore1600/   the ported kernel (TMA -> cooperative `ldg`, mbarrier ->
#                     single buffer + `__syncthreads`, inline PTX -> MACA
#                     builtins).  Its config tuples are re-derived for 128 KiB
#                     by `scripts/generate_instantiations.py` and checked
#                     against that capacity at compile time.  xcore1500 shares
#                     this tree: same capacity, same table.
#
# `csrc/structs.h` stays at the top: both halves include it.
# `csrc/xcore1600/v3_cluster` was deleted with the cluster variant -- MACA has
# no cluster launch.
XCORE1000_SOURCES = [
    "csrc/xcore1000/maca_topk.cu",
]


def _xcore1600_sources():
    """The ported kernel: host dispatch plus every instantiation.

    The instantiation files are generated by
    `scripts/generate_instantiations.py` and listed explicitly, as upstream
    lists them in its own `setup.py`: the set is what gets compiled, so it
    should be visible, not globbed.
    """
    sources = ["csrc/xcore1600/api.cpp"]
    for variant in ("v3", "v3_fp32"):
        directory = os.path.join("csrc", "xcore1600", variant, "instantiations")
        sources += sorted(
            os.path.join(directory, name)
            for name in os.listdir(directory)
            if name.endswith(".cu")
        )
    return sources


def _maca_root() -> str:
    return os.environ.get("MACA_HOME") or os.environ.get("MACA_PATH") or "/opt/maca"


# torch compiles a `.cpp` source with `$cxx`, whose default is `c++` -- and on
# this platform PATH resolves `c++` to cu-bridge's compiler wrapper, which is
# not a compiler.  `g++` is not shadowed there, and GCC is the host compiler the
# MACA toolchain itself uses (`api.cpp` carries a note about `<format>` being
# absent from GCC 11 for exactly this reason).
_HOST_CXX = "g++"


# torch's CUDAExtension drives its device compiler as `$CUDA_HOME/bin/nvcc`, in
# CUDA's flag dialect.  On MACA that path is cu-bridge's `cucc` -- a shell
# wrapper that translates the flags and then runs mxcc (`cucc`:989-996, :1133).
# This hands torch that same shape backed by mxcc directly, so the compiler is
# the one named on the tin and the translation is written down here instead of
# being inferred from a shell script.
#
# Only torch's own flags need translating: what this repository passes in
# `extra_compile_args` (below) is written in mxcc's dialect already, and every
# flag not named here reaches mxcc unchanged -- so an unsupported one is
# reported by mxcc with its name rather than silently dropped here.
_MXCC_NVCC_WRAPPER = """#!/bin/bash
set -e
mxcc="%(mxcc)s"
args=()
dep_file=""
want_dep=0
while [ $# -gt 0 ]; do
  case "$1" in
    # torch's dependency plumbing, in nvcc's spelling; mxcc takes clang's.
    --generate-dependencies-with-compile) want_dep=1 ;;
    --dependency-output) shift; dep_file="$1" ;;
    # `-gencode=arch=compute_XY,code=sm_XY`, derived by torch from the visible
    # device or from TORCH_CUDA_ARCH_LIST.  mxcc rejects it outright, and the
    # architecture that matters here is `--offload-arch`, which setup.py passes
    # per extension.  Dropping it also makes the build independent of which
    # device happens to be visible while building: one extension, one arch.
    -gencode=*) ;;
    # In torch's COMMON_NVCC_FLAGS.  clang relaxes constexpr by default and has
    # no such option.
    --expt-relaxed-constexpr) ;;
    # torch routes host flags through nvcc for its host compiler.  The only one
    # it passes is `-fPIC`, which setup.py passes directly instead.
    --compiler-options) shift ;;
    *) args+=("$1") ;;
  esac
  shift
done
[ "$want_dep" = 1 ] && args+=("-MMD")
[ -n "$dep_file" ] && args+=("-MF" "$dep_file")
# cu-bridge's compatibility header, which cucc adds to every invocation.  mxcc
# defines `__MACACC__` and this turns it into `__CUDACC__`/`__NVCC__` -- the
# macros torch's c10 and the rest of the CUDA-facing headers branch on.  Without
# it `c10::Half` declares no conversion to `__half` while `Half-inl.h` still
# takes its MACA branch (`__MACA_ARCH__`), and the device pass fails to compile.
# cucc passes it as `-imacros`, which mxcc's own argument parser rejects;
# `-include` does the same thing for a header that only defines macros.  It is
# found through the cu-bridge include dir, which setup.py puts on the path.
args+=("-include" "__macro_mxcc.h")
exec "$mxcc" "${args[@]}"
"""


def _prepare_mxcc_home(maca_root: str, this_dir: str) -> str:
    """Write the wrapper and return a `CUDA_HOME` pointing at it.

    Also the one piece of library plumbing torch expects of a CUDA_HOME: it
    links a device extension against `-lcudart`, searched in `$CUDA_HOME/lib64`.
    MACA's CUDA runtime is `libmcruntime.so`, and the name `libcudart.so` is a
    link to it -- which is how the vendor's own CUDA_DIR ships it, and why the
    linked extension records `libmcruntime.so` (the runtime it really runs on)
    rather than a cudart it would never load.
    """
    home = os.path.join(this_dir, "build", "maca_cuda_home")
    os.makedirs(os.path.join(home, "bin"), exist_ok=True)
    os.makedirs(os.path.join(home, "include"), exist_ok=True)
    nvcc = os.path.join(home, "bin", "nvcc")
    with open(nvcc, "w", encoding="utf-8") as f:
        f.write(_MXCC_NVCC_WRAPPER % {
            "mxcc": os.path.join(maca_root, "mxgpu_llvm", "bin", "mxcc"),
        })
    os.chmod(nvcc, 0o755)

    lib64 = os.path.join(home, "lib64")
    os.makedirs(lib64, exist_ok=True)
    cudart = os.path.join(lib64, "libcudart.so")
    if not os.path.lexists(cudart):      # lexists: a stale broken link counts
        os.symlink(os.path.join(maca_root, "lib", "libmcruntime.so"), cudart)
    return home


def build_for_maca():
    """Build one extension per architecture, each holding that architecture's
    kernel.

    Which kernel an architecture gets is a property of the architecture, not a
    build-time choice: 64 KiB parts run `csrc/xcore1000/`, 128 KiB parts run
    `csrc/xcore1600/`.  Each is built as its own extension, named for the
    architecture it serves -- `deep_select.deep_select_xcore<N>` -- because a
    config's shared memory footprint is only valid for the architecture it was
    sized for, and because `deep_select.topk`'s `backend=` selects among them
    by exactly that name.

    Which architectures get built comes from `CUCC_TARGETS` (default
    `native`), the same variable and meaning as the host repository's
    `build.sh`.

    Device code is compiled by `mxcc` (MACA's nvcc equivalent) directly.  torch
    finds its device compiler at `$CUDA_HOME/bin/nvcc`, so `CUDA_HOME` is
    pointed at a directory written for this build holding one script under that
    name (`_prepare_mxcc_home`); the script translates the few CUDA-dialect
    flags torch injects and hands the rest to mxcc.  The `-gencode
    arch=compute_XY,code=sm_XY` torch derives from the visible device is among
    those translated away -- the architecture comes from `--offload-arch` here,
    one per extension.

    Host code is not: torch compiles a `.cpp` source with `$cxx`, not `$nvcc`,
    so `CXX` is set to `g++`.  It has to be named explicitly because PATH puts
    cu-bridge's `bin` -- which holds a compiler wrapper under the name `c++` --
    ahead of the system compiler.  `api.cpp` is the one `.cpp` here, and it
    needs `-DKERUTILS_IS_BUILD_ON_CUDA`: kerutils defines that macro itself for
    a CUDA compilation (`kerutils/common/common.h`), and a plain host compile
    is not one.

    `--offload-arch` overrides `CUCC_TARGETS` in the environment, so passing it
    explicitly per module is what keeps the modules independent of each
    other's builds -- and that independence is the point: a tuple that cannot
    fit the architecture being built is a compile error, which only works if a
    compilation targets exactly one architecture.
    """
    import torch.utils.cpp_extension as cpp_extension
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension

    from deep_select._arch import (CAPACITY_BYTES, family_of_target,
                                   kernel_directory, resolve_targets)

    maca_root = _maca_root()
    this_dir = os.path.dirname(os.path.abspath(__file__))
    targets = resolve_targets(os.environ.get("CUCC_TARGETS"))

    # A config's shared memory footprint is valid for exactly one architecture,
    # so a build targets exactly one.  torch's MACA build appends a second
    # `--offload-arch` of its own when this is set, which would put two of them
    # in one extension -- a config sized for 128 KiB silently riding along into
    # a 64 KiB build.  Refuse rather than build something that is wrong on one
    # of the two architectures it claims.
    if os.environ.get("TORCH_EXTENSION_ENABLE_XC1500_COMPILE"):
        raise RuntimeError(
            "TORCH_EXTENSION_ENABLE_XC1500_COMPILE makes torch append "
            "--offload-arch=xcore1000/xcore1500 to every source; setup.py "
            "targets one architecture per extension.  Unset it and pass the "
            "architectures to build via CUCC_TARGETS instead."
        )

    # Hand torch a CUDA_HOME whose `bin/nvcc` is mxcc, so the device compiler is
    # mxcc itself and not cu-bridge's wrapper around it.  torch reads this
    # through the module global, which is why it is assigned rather than passed.
    cpp_extension.CUDA_HOME = _prepare_mxcc_home(maca_root, this_dir)
    # `api.cpp` goes to the host compiler; see the docstring.  Assigned rather
    # than passed for the same reason as CUDA_HOME.
    os.environ["CXX"] = _HOST_CXX
    print(f"deep_select: device compiler is "
          f"{os.path.join(cpp_extension.CUDA_HOME, 'bin', 'nvcc')}, "
          f"host compiler is {_HOST_CXX}")

    # cucc appends this catalogue to every invocation (`cucc`:989ff and its
    # conf), so it is part of the flags the kernels were developed against even
    # though torch's ninja file never mentions it.  `soft-link/cutlass` is the
    # load-bearing one: `cutlass/kernel_launch.h` exists only there, as a
    # symlink to `mctlass/`, and `cutlass/cutlass.h` in the directory next door
    # is a 126-byte forwarder.
    maca_library_includes = ["mcr", "mcblas", "mcfft", "mcsolver", "mcdnn",
                             "common", "mcsparse", "mcrand", "mckl", "mcsml",
                             "mctx", "thrust/detail"]

    include_dirs = [
        os.path.join(this_dir, "csrc"),
        # The ported kernel's own headers are included unqualified
        # (`#include "config.h"`), which keeps them independent of where this
        # directory sits.
        os.path.join(this_dir, "csrc", "xcore1600"),
        # `kerutils/kerutils.cuh` and `kerutils/supplemental/torch_tensors.h`,
        # which `api.cpp` and the ported kernels include.  Vendored under
        # `csrc/3rdparty`; upstream's own build gets this path from its
        # `3rdparty/kerutils` layout, so it is spelled out here rather than
        # guessed from the sources.
        os.path.join(this_dir, "csrc", "3rdparty", "kerutils", "include"),
        os.path.join(maca_root, "include"),
        os.path.join(maca_root, "tools", "cu-bridge", "include"),
        os.path.join(maca_root, "tools", "cu-bridge", "include", "soft-link"),
    ] + [os.path.join(maca_root, "include", d) for d in maca_library_includes]

    def compile_args(target):
        # In mxcc's dialect, because these go to mxcc: the wrapper above only
        # translates what torch injects, and adds "-" to nothing else.
        args = [
            "-O3",
            "-std=c++20",
            "-DNDEBUG",
            "-Wno-deprecated-declarations",
            # torch passes `-fPIC` to the host compiler and, for device code,
            # as `--compiler-options '-fPIC'` -- which the wrapper drops along
            # with the rest of torch's host flags, so it is named here.
            "-fPIC",
            "-use-fast-math",
            # `-use-fast-math` implies FTZ, so it is turned back off here.
            # The ranking path cannot care either way: it is pure integer
            # manipulation of the key (`__float_as_uint` plus integer ops),
            # and FTZ only governs floating-point arithmetic and conversion
            # results.  Keeping it off keeps the one float conversion in the
            # kernel -- `__float2bfloat16` of `value_oob_fill_value` -- exact
            # for a denormal fill instead of flushing it to zero.
            "-Xclang", "-fdenormal-fp-math-f32=ieee",
            f"-offload-arch={target}",
            # `__MACA_ARCH__` is only defined in the device pass, but the
            # capacity constant lives in `structs.h`, which every translation
            # unit here includes -- so the value has to be spelled out on the
            # command line.  It carries the same number the toolchain derives,
            # and setup.py sets both from the same loop iteration.
            f"-DDEEP_SELECT_NATIVE_ARCH={family_of_target(target)}",
        ]
        return args + [f"-I{d}" for d in include_dirs]

    ext_modules = []
    for target in targets:
        family = family_of_target(target)
        capacity_kib = CAPACITY_BYTES[family] // 1024
        # Every architecture gets the kernel that was built for its capacity,
        # so there is no opt-in and no skip: an architecture with no kernel
        # would be a hole in `backend=`, not a smaller build.
        if kernel_directory(family) == "xcore1000":
            sources = XCORE1000_SOURCES
            which = "the MACA-native kernel"
        else:
            sources = _xcore1600_sources()
            which = "the ported kernel"
        ext_modules.append(
            CUDAExtension(
                name=f"deep_select.deep_select_xcore{family}",
                sources=sources,
                include_dirs=include_dirs,
                extra_compile_args={
                    "cxx": [
                        "-O3",
                        "-std=c++17",
                        "-DNDEBUG",
                        "-Wno-deprecated-declarations",
                        # kerutils defines this itself for a CUDA compilation
                        # (`kerutils/common/common.h`) and errors out without
                        # it; torch compiles `api.cpp` with the host compiler,
                        # which is not one.
                        "-DKERUTILS_IS_BUILD_ON_CUDA",
                        f"-DDEEP_SELECT_NATIVE_ARCH={family}",
                    ],
                    "nvcc": compile_args(target),
                },
                extra_link_args=[
                    f"-L{maca_root}/lib",
                    f"-Wl,-rpath,{maca_root}/lib",
                ],
                define_macros=[("DEEP_SELECT_TARGET", f'"{target}"')],
            )
        )
        print(f"deep_select: building xcore{family} "
              f"({capacity_kib} KiB shared memory) for {target}: {which}")

    return (ext_modules, BuildExtension.with_options(use_ninja=True))


try:
    cmd = ["git", "rev-parse", "--short", "HEAD"]
    git_rev = subprocess.check_output(cmd, stderr=subprocess.DEVNULL).decode("ascii").rstrip()
except Exception:
    # e.g. building from a source tarball that has no `.git`. Keep the version
    # a valid PEP 440 local version in that case.
    git_rev = "unknown"

datetime_rev = datetime.now().strftime("%Y%m%d.%H%M%S")

ext_modules, build_ext = build_for_maca()

setup(
    name="deep_select",
    version=f"{__version__}+{git_rev}.{datetime_rev}",
    packages=find_packages(include=["deep_select"]),
    ext_modules=ext_modules,
    cmdclass={"build_ext": build_ext},
    zip_safe=False,
)
