import os
import subprocess
from datetime import datetime
from pathlib import Path

from setuptools import setup, find_packages

exec(open("deep_select/__version__.py").read())

# The kernel tree is split by architecture, and each half is a kernel rather
# than a variant of one:
#
#   csrc/xcore1000/   the hand-written MACA kernel (`maca_topk.cu`).  No
#                     capacity gate and no architecture-specific code; this is
#                     what a 64 KiB part runs.
#   csrc/xcore1600/   the ported kernel (TMA -> cooperative `ldg`, mbarrier ->
#                     single buffer + `__syncthreads`, inline PTX -> MACA
#                     builtins).  Its config tuples are re-derived for 128 KiB
#                     by `scripts/generate_instantiations.py` and checked
#                     against that capacity at compile time.  xcore1500 shares
#                     this tree: same capacity, same table.
#
# `csrc/structs.h` stays at the top: both halves include it.
# `csrc/xcore1600/v3_cluster` was deleted with the cluster variant -- MACA has
# no cluster launch.
XCORE1000_SOURCES = [
    "csrc/xcore1000/maca_topk.cu",
]


def _xcore1600_sources():
    """The ported kernel: host dispatch plus every instantiation.

    The instantiation files are generated by
    `scripts/generate_instantiations.py` and listed explicitly, as upstream
    lists them in its own `setup.py`: the set is what gets compiled, so it
    should be visible, not globbed.
    """
    sources = ["csrc/xcore1600/api.cu"]
    for variant in ("v3", "v3_fp32"):
        directory = os.path.join("csrc", "xcore1600", variant, "instantiations")
        sources += sorted(
            os.path.join(directory, name)
            for name in os.listdir(directory)
            if name.endswith(".cu")
        )
    return sources


def _maca_root() -> str:
    return os.environ.get("MACA_HOME") or os.environ.get("MACA_PATH") or "/opt/maca"


# The host compiler and linker, and not a detail that can be left to the
# environment: this torch build installs its own `CXX` at import time.  MACA's
# `torch/utils/cpp_extension.py` carries a patch --
#
#     def set_wcuda_gnu_path():                            # ~:62
#         gnu_path = os.path.join(CUDA_HOME, 'bin', 'gnu')
#         if os.path.exists(gnu_path):
#             os.environ['CXX'] = gnu_path
#     ...
#     CUDA_HOME = _find_cuda_home() ...
#     set_wcuda_gnu_path()                                 # ~:286, at import
#
# -- and `get_cxx_compiler()` is just `os.environ.get('CXX', 'c++')`.  With the
# default CUDA_HOME (`_find_cuda_home`'s cu-bridge guard) that path exists, so
# `CXX` is silently repointed at cu-bridge's `bin/gnu`, a wrapper that execs
# mxcc.  Reassigning `cpp_extension.CUDA_HOME` below does *not* undo it: the
# patch already ran at import, against the old value.
#
# It matters even though every source here is a `.cu`, because ninja links with
# `$cxx` (`command = $cxx $in $ldflags -o $out`).  Left alone, the extension is
# linked by cu-bridge's wrapper; measured, that changes the artifact's md5.
# Whatever upstream leaves informal, this file fixes explicitly.
_HOST_CXX = "g++"


# torch's CUDAExtension drives its device compiler as `$CUDA_HOME/bin/nvcc`, in
# CUDA's flag dialect.  On MACA that path is cu-bridge's `cucc` -- a shell
# wrapper that translates the flags and then runs mxcc (`cucc`:989-996, :1133).
# This hands torch that same shape backed by mxcc directly, so the compiler is
# the one named on the tin and the translation is written down here instead of
# being inferred from a shell script.
#
# Only torch's own flags need translating: what this repository passes in
# `extra_compile_args` (below) is written in mxcc's dialect already, and every
# flag not named here reaches mxcc unchanged -- so an unsupported one is
# reported by mxcc with its name rather than silently dropped here.
_MXCC_NVCC_WRAPPER = """#!/bin/bash
set -e
mxcc="%(mxcc)s"
args=()
dep_file=""
want_dep=0
while [ $# -gt 0 ]; do
  case "$1" in
    # torch's dependency plumbing, in nvcc's spelling; mxcc takes clang's.
    --generate-dependencies-with-compile) want_dep=1 ;;
    --dependency-output) shift; dep_file="$1" ;;
    # `-gencode=arch=compute_XY,code=sm_XY`, derived by torch from the visible
    # device or from TORCH_CUDA_ARCH_LIST.  mxcc rejects it outright, and the
    # architecture that matters here is `--offload-arch`, which setup.py passes
    # per extension.  Dropping it also makes the build independent of which
    # device happens to be visible while building: one extension, one arch.
    -gencode=*) ;;
    # In torch's COMMON_NVCC_FLAGS.  clang relaxes constexpr by default and has
    # no such option.
    --expt-relaxed-constexpr) ;;
    # torch routes host flags through nvcc for its host compiler.  The only one
    # it passes is `-fPIC`, which setup.py passes directly instead.
    --compiler-options) shift ;;
    *) args+=("$1") ;;
  esac
  shift
done
[ "$want_dep" = 1 ] && args+=("-MMD")
[ -n "$dep_file" ] && args+=("-MF" "$dep_file")
# cu-bridge's compatibility header, which cucc adds to every invocation.  mxcc
# defines `__MACACC__` and this turns it into `__CUDACC__`/`__NVCC__` -- the
# macros torch's c10 and the rest of the CUDA-facing headers branch on.  Without
# it `c10::Half` declares no conversion to `__half` while `Half-inl.h` still
# takes its MACA branch (`__MACA_ARCH__`), and the device pass fails to compile.
# cucc passes it as `-imacros`, which mxcc's own argument parser rejects;
# `-include` does the same thing for a header that only defines macros.  It is
# found through the cu-bridge include dir, which setup.py puts on the path.
args+=("-include" "__macro_mxcc.h")
exec "$mxcc" "${args[@]}"
"""


def _prepare_mxcc_home(maca_root: str, this_dir: str) -> str:
    """Write the wrapper and return a `CUDA_HOME` pointing at it.

    Also the one piece of library plumbing torch expects of a CUDA_HOME: it
    links a device extension against `-lcudart`, searched in `$CUDA_HOME/lib64`.
    MACA's CUDA runtime is `libmcruntime.so`, and the name `libcudart.so` is a
    link to it -- which is how the vendor's own CUDA_DIR ships it, and why the
    linked extension records `libmcruntime.so` (the runtime it really runs on)
    rather than a cudart it would never load.
    """
    home = os.path.join(this_dir, "build", "maca_cuda_home")
    os.makedirs(os.path.join(home, "bin"), exist_ok=True)
    os.makedirs(os.path.join(home, "include"), exist_ok=True)
    nvcc = os.path.join(home, "bin", "nvcc")
    with open(nvcc, "w", encoding="utf-8") as f:
        f.write(_MXCC_NVCC_WRAPPER % {
            "mxcc": os.path.join(maca_root, "mxgpu_llvm", "bin", "mxcc"),
        })
    os.chmod(nvcc, 0o755)

    lib64 = os.path.join(home, "lib64")
    os.makedirs(lib64, exist_ok=True)
    cudart = os.path.join(lib64, "libcudart.so")
    if not os.path.lexists(cudart):      # lexists: a stale broken link counts
        os.symlink(os.path.join(maca_root, "lib", "libmcruntime.so"), cudart)
    return home


def build_for_maca():
    """Build one extension per architecture, each holding that architecture's
    kernel.

    Which kernel an architecture gets is a property of the architecture, not a
    build-time choice: 64 KiB parts run `csrc/xcore1000/`, 128 KiB parts run
    `csrc/xcore1600/`.  Each is built as its own extension, named for the
    architecture it serves -- `deep_select.deep_select_xcore<N>` -- because a
    config's shared memory footprint is only valid for the architecture it was
    sized for, and because `topk(backend="maca_c")` resolves to one of them by
    exactly that name -- the architecture is named here, in the build, and not
    in the public `backend=`.

    Which architectures get built comes from `CUCC_TARGETS` (default
    `native`), the same variable and meaning as the host repository's
    `build.sh`.

    Device code is compiled by `mxcc` (MACA's nvcc equivalent) directly.  torch
    finds its device compiler at `$CUDA_HOME/bin/nvcc`, so `CUDA_HOME` is
    pointed at a directory written for this build holding one script under that
    name (`_prepare_mxcc_home`); the script translates the few CUDA-dialect
    flags torch injects and hands the rest to mxcc.  The `-gencode
    arch=compute_XY,code=sm_XY` torch derives from the visible device is among
    those translated away -- the architecture comes from `--offload-arch` here,
    one per extension.

    Every source is a `.cu`, so `$nvcc` -- the shim above -- is the only
    compiler this build invokes: torch routes a `.cpp` source to `$cxx`
    instead (`cpp_extension._is_cuda_file`), and a second compiler would mean a
    second flag list, a second kerutils mode macro and a pinned `CXX` to keep
    working.  `csrc/xcore1600/api.cu` carries the reasoning for why upstream's
    `api.cu` is spelled that way here.

    `--offload-arch` overrides `CUCC_TARGETS` in the environment, so passing it
    explicitly per module is what keeps the modules independent of each
    other's builds -- and that independence is the point: a tuple that cannot
    fit the architecture being built is a compile error, which only works if a
    compilation targets exactly one architecture.
    """
    import torch.utils.cpp_extension as cpp_extension
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension

    from deep_select._arch import (CAPACITY_BYTES, family_of_target,
                                   kernel_directory, resolve_targets)

    maca_root = _maca_root()
    this_dir = os.path.dirname(os.path.abspath(__file__))
    targets = resolve_targets(os.environ.get("CUCC_TARGETS"))

    # A config's shared memory footprint is valid for exactly one architecture,
    # so a build targets exactly one.  torch's MACA build appends a second
    # `--offload-arch` of its own when this is set, which would put two of them
    # in one extension -- a config sized for 128 KiB silently riding along into
    # a 64 KiB build.  Refuse rather than build something that is wrong on one
    # of the two architectures it claims.
    if os.environ.get("TORCH_EXTENSION_ENABLE_XC1500_COMPILE"):
        raise RuntimeError(
            "TORCH_EXTENSION_ENABLE_XC1500_COMPILE makes torch append "
            "--offload-arch=xcore1000/xcore1500 to every source; setup.py "
            "targets one architecture per extension.  Unset it and pass the "
            "architectures to build via CUCC_TARGETS instead."
        )

    # Hand torch a CUDA_HOME whose `bin/nvcc` is mxcc, so the device compiler is
    # mxcc itself and not cu-bridge's wrapper around it.  torch reads this
    # through the module global, which is why it is assigned rather than passed.
    cpp_extension.CUDA_HOME = _prepare_mxcc_home(maca_root, this_dir)
    # Undo the `set_wcuda_gnu_path` patch above, which is what `CXX` holds by
    # now; ninja links with it even though every source here is a `.cu`.  See
    # `_HOST_CXX`.
    os.environ["CXX"] = _HOST_CXX
    print(f"deep_select: device compiler is "
          f"{os.path.join(cpp_extension.CUDA_HOME, 'bin', 'nvcc')}, "
          f"host compiler is {_HOST_CXX}")

    # cucc appends this catalogue to every invocation (`cucc`:989ff and its
    # conf), so it is part of the flags the kernels were developed against even
    # though torch's ninja file never mentions it.  `soft-link/cutlass` is the
    # load-bearing one: `cutlass/kernel_launch.h` exists only there, as a
    # symlink to `mctlass/`, and `cutlass/cutlass.h` in the directory next door
    # is a 126-byte forwarder.
    maca_library_includes = ["mcr", "mcblas", "mcfft", "mcsolver", "mcdnn",
                             "common", "mcsparse", "mcrand", "mckl", "mcsml",
                             "mctx", "thrust/detail"]

    include_dirs = [
        os.path.join(this_dir, "csrc"),
        # The ported kernel's own headers are included unqualified
        # (`#include "config.h"`), which keeps them independent of where this
        # directory sits.
        os.path.join(this_dir, "csrc", "xcore1600"),
        # `kerutils/kerutils.cuh` and `kerutils/supplemental/torch_tensors.h`,
        # which the ported kernels include.  Vendored under
        # `csrc/3rdparty`; upstream's own build gets this path from its
        # `3rdparty/kerutils` layout, so it is spelled out here rather than
        # guessed from the sources.
        os.path.join(this_dir, "csrc", "3rdparty", "kerutils", "include"),
        os.path.join(maca_root, "include"),
        os.path.join(maca_root, "tools", "cu-bridge", "include"),
        os.path.join(maca_root, "tools", "cu-bridge", "include", "soft-link"),
    ] + [os.path.join(maca_root, "include", d) for d in maca_library_includes]

    def compile_args(target):
        # In mxcc's dialect, because these go to mxcc: the wrapper above only
        # translates what torch injects, and adds "-" to nothing else.
        args = [
            "-O3",
            "-std=c++20",
            "-DNDEBUG",
            "-Wno-deprecated-declarations",
            # torch passes `-fPIC` to the host compiler and, for device code,
            # as `--compiler-options '-fPIC'` -- which the wrapper drops along
            # with the rest of torch's host flags, so it is named here.
            "-fPIC",
            "-use-fast-math",
            # `-use-fast-math` implies FTZ, so it is turned back off here.
            # The ranking path cannot care either way: it is pure integer
            # manipulation of the key (`__float_as_uint` plus integer ops),
            # and FTZ only governs floating-point arithmetic and conversion
            # results.  Keeping it off keeps the one float conversion in the
            # kernel -- `__float2bfloat16` of `value_oob_fill_value` -- exact
            # for a denormal fill instead of flushing it to zero.
            "-Xclang", "-fdenormal-fp-math-f32=ieee",
            f"-offload-arch={target}",
            # `__MACA_ARCH__` is only defined in the device pass, but the
            # capacity constant lives in `structs.h`, which every translation
            # unit here includes -- so the value has to be spelled out on the
            # command line.  It carries the same number the toolchain derives,
            # and setup.py sets both from the same loop iteration.
            f"-DDEEP_SELECT_NATIVE_ARCH={family_of_target(target)}",
        ]
        return args + [f"-I{d}" for d in include_dirs]

    ext_modules = []
    for target in targets:
        family = family_of_target(target)
        capacity_kib = CAPACITY_BYTES[family] // 1024
        # Every architecture gets the kernel that was built for its capacity,
        # so there is no opt-in and no skip: an architecture with no kernel
        # would be a hole in `backend="maca_c"`, not a smaller build.
        if kernel_directory(family) == "xcore1000":
            sources = XCORE1000_SOURCES
            which = "the MACA-native kernel"
        else:
            sources = _xcore1600_sources()
            which = "the ported kernel"
        ext_modules.append(
            CUDAExtension(
                name=f"deep_select.deep_select_xcore{family}",
                sources=sources,
                include_dirs=include_dirs,
                # Every source is a `.cu`, so the `nvcc` list is the only one
                # torch ever reads; the key is torch's name for "the device
                # source list", and its contents are mxcc's dialect because
                # `bin/nvcc` is the shim above.
                extra_compile_args={
                    "nvcc": compile_args(target),
                },
                extra_link_args=[
                    f"-L{maca_root}/lib",
                    f"-Wl,-rpath,{maca_root}/lib",
                ],
            )
        )
        print(f"deep_select: building xcore{family} "
              f"({capacity_kib} KiB shared memory) for {target}: {which}")

    return (ext_modules, BuildExtension.with_options(use_ninja=True))


# --- stack-frame check (the MACA counterpart of upstream's spill gate) ------
#
# Upstream's `setup.py` runs `SpillCheckBuildExtension`: after the build, every
# extension is scanned with `cuobjdump -res-usage` and the build *fails* on a
# kernel that spills (`stack > 8 or local > 0`).  There is no `cuobjdump` on a
# MACA install, so the reference artifact check cannot run here; mxcc's own
# `--resource-usage` stands in for it, through
# `tests.kernelkit.build.check_maca_stack_frame`.
#
# It is not wired into `build_ext` by default, and that is a measurement rather
# than a preference: `--resource-usage` recompiles the translation unit it is
# asked about, which is ~60 s for `maca_topk.cu` (one TU, 78 device functions)
# and tens of minutes for one xcore1600 instantiation -- and xcore1600 builds
# 52 of them.  So it is opt-in, over a named subset of sources:
#
#     DEEP_SELECT_MACA_STACK_CHECK=1 ./build.sh
#     DEEP_SELECT_MACA_STACK_CHECK=csrc/xcore1000/maca_topk.cu ./build.sh
#     DEEP_SELECT_MACA_STACK_BASELINE=64 DEEP_SELECT_MACA_STACK_CHECK=1 ./build.sh
#
# The baseline is in bytes and must be set per toolchain: with this one, 50 of
# the 78 devices in `maca_topk.cu` floor at 48 (the other 28 report 0) -- so a
# baseline of 47 reports every one of them and a baseline of 49 reports none,
# which makes 48 the only value that separates "the toolchain's floor" from an
# actual spill.  Upstream's `stack_baseline=8` does not carry over: it predates
# a toolchain whose floor is nonzero.  A kernel over the baseline fails the
# build, as upstream's does.
DEFAULT_MACA_STACK_BASELINE = 48


def _maca_stack_check(ext_modules, maca_root):
    """Scan the sources behind a built extension, if the caller asked for it.

    The sources are taken from the extensions themselves, so the check follows
    whatever was actually built rather than a list repeated here.
    """
    want = os.environ.get("DEEP_SELECT_MACA_STACK_CHECK")
    if not want or want.lower() in ("0", "no", "false"):
        return

    import sys as _sys

    _sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from tests.kernelkit.build import check_maca_stack_frame

    selected = [] if want.lower() in ("1", "yes", "true") \
        else [s.strip() for s in want.split(",")]
    baseline = int(os.environ.get("DEEP_SELECT_MACA_STACK_BASELINE",
                                  DEFAULT_MACA_STACK_BASELINE))
    mxcc = os.path.join(maca_root, "mxgpu_llvm", "bin", "mxcc")

    root = os.getcwd()
    bad = 0
    for ext in ext_modules:
        # The device-side flags the build already resolved for this extension,
        # so the check compiles the way the build did rather than a second,
        # hand-maintained copy of the same list.  Torch's own include paths are
        # *not* in there -- `build_for_maca` gives them to `CUDAExtension`,
        # which merges them in later -- so the checker adds them itself.
        args = list(ext.extra_compile_args["nvcc"])
        for src in ext.sources:
            if selected:
                rel = os.path.relpath(src, root).replace(os.sep, "/")
                if not any(rel.endswith(s) or s.endswith(rel) for s in selected):
                    continue
            hits = check_maca_stack_frame(src, baseline, mxcc, args, quiet=False)
            bad += len(hits)
    if bad:
        raise RuntimeError(
            f"{bad} MACA kernel(s) exceed the stack baseline of {baseline} B. "
            f"Spilling degrades these kernels; raise "
            f"DEEP_SELECT_MACA_STACK_BASELINE only if the reading is expected, "
            f"and unset DEEP_SELECT_MACA_STACK_CHECK to skip the check.")


try:
    cmd = ["git", "rev-parse", "--short", "HEAD"]
    git_rev = subprocess.check_output(cmd, stderr=subprocess.DEVNULL).decode("ascii").rstrip()
except Exception:
    # e.g. building from a source tarball that has no `.git`. Keep the version
    # a valid PEP 440 local version in that case.
    git_rev = "unknown"

datetime_rev = datetime.now().strftime("%Y%m%d.%H%M%S")

ext_modules, build_ext = build_for_maca()

# Before the build, not after: `--resource-usage` compiles the source itself,
# so there is nothing to gain by waiting for the wheel.  Sources are listed
# relative to this file, which is therefore the root to resolve against.
_maca_stack_check(ext_modules, _maca_root())

setup(
    name="deep_select",
    version=f"{__version__}+{git_rev}.{datetime_rev}",
    packages=find_packages(include=["deep_select"]),
    ext_modules=ext_modules,
    cmdclass={"build_ext": build_ext},
    zip_safe=False,
)
